#' exampleGenomePileupSubset
#'
#' A subset of the sampleGenomePileup used to demonstrate code in examples in
#' under 10 seconds.
#' Report...
#'
#' @keywords internal
#' @format ## `exampleGenomePileupSubset`
#' A data frame with 3,500 rows and 4 columns:
#' \describe{
#'   \item{V1}{Accession}
#'   \item{V2}{Mapped read coverage averaged over a 100 bp window size}
#'   \item{V3}{Starting position (bp) of each 100 bp window. Starts from 100.}
#'   \item{V4}{Starting position (bp) of each 100 bp window. Starts from 0.}
#' }
#' @details This dataset is a subset of the sampleGenomePileup generated by running:
#' "exampleGenomePileupSubset <- sampleGenomePileup[which(sampleGenomePileup[,3]<=350000),]"
"exampleGenomePileupSubset"
