#' sampleGenomegffTSV
#'
#' Gene annotations associated with the genome in the sampleGenomePileup
#' Report...
#'
#' @keywords internal
#' @format ## `sampleGenomegffTSV`
#' A data frame with 85,575 rows and 9 columns:
#' \describe{
#'   \item{V1}{seqid}
#'   \item{V2}{source}
#'   \item{V3}{type}
#'   \item{V4}{start}
#'   \item{V5}{end}
#'   \item{V6}{score}
#'   \item{V7}{strand}
#'   \item{V8}{phase}
#'   \item{V9}{attributes}
#' }
#' @details This is a standard .gff file format. The .gff file was generated by
#' running PROKKA with default parameters on the *Salmonella enterica* LT2 genome
#' sequence  (NCBI RefSeq NC_003197.2) associated with the sampleGenomePileup in
#' the ProActive package.
"sampleGenomegffTSV"
